-- Apply this SQL in the Supabase SQL editor before using /admin/convenios.
-- The Supabase CLI is not available in this repo, so this file is kept as the
-- reproducible database/storage setup for Convenios.

create table if not exists public.convenios (
  id bigint generated by default as identity primary key,
  nombre text not null check (length(trim(nombre)) > 0),
  descuento integer not null default 0 check (descuento >= 0 and descuento <= 100),
  logo_url text,
  link_url text not null check (link_url ~* '^https?://'),
  banner_grande_url text,
  banner_chico_url text,
  banner_modo text not null default 'placeholder' check (banner_modo in ('placeholder', 'imagen')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.convenios enable row level security;

drop policy if exists "Convenios are visible to everyone" on public.convenios;
create policy "Convenios are visible to everyone"
on public.convenios
for select
to anon, authenticated
using (true);

grant select on public.convenios to anon, authenticated;
revoke insert, update, delete on public.convenios from anon, authenticated;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'convenio-assets',
  'convenio-assets',
  true,
  5242880,
  array['image/webp', 'image/avif', 'image/png', 'image/jpeg']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
